### ISSUE TITLE
Can not play the modpack

### ISSUE THREAD

**Issue by Fulmetalmon** [Freebi85/Dungeons-Dragons-Space-Shuttles#384]
I can not load the modback i click play then it just crashes before even popping up the game window
.could someone help me fix this.

this is what the log shows

[21:27:58] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:27:58] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:27:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:27:58] [main/INFO]: Forge Mod Loader version 14.23.5.2836 for Minecraft 1.12.2 loading
[21:27:58] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Curse\Minecraft\Install\runtime\jre-x64
[21:27:59] [main/INFO]: Searching D:\Curse\Minecraft\Instances\Dungeons, Dragons and Space Shuttles\mods for mods
[21:27:59] [main/INFO]: Searching D:\Curse\Minecraft\Instances\Dungeons, Dragons and Space Shuttles\mods\1.12.2 for mods
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.20.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/INFO]: [AstralCore] Initialized.
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in bedpatch-2.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.9.67_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.20.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in DynamicSurroundings-1.12.2-3.4.9.17.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod org.blockartistry.DynSurround.asm.TransformLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in elulib-0.1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod FMLPlugin (elucent.elulib.asm.FMLPlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Farseek-1.12-2.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod FarseekCoreMod (farseek.core.FarseekCoreMod) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.5-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ForgeEndertech-1.12.2-4.4.0.0-build.0180.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod com.endertech.minecraft.forge.coremod.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod CorePlugin (com.endertech.minecraft.forge.coremod.CorePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HammerCore-1.12.2-2.0.5.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64+dev.146.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.19.2-release.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre167_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.4.0.jar
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.7.9.380.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[21:27:59] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.4.153.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in p455w0rdslib-1.12.2-2.2.156.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.5-130.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-177.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[21:27:59] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SGCraft-2.0.2.jar
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Sledgehammer-1.12.2-1.6.5.jar
[21:27:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:27:59] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-99.jar
[21:27:59] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[21:27:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:27:59] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:27:59] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[21:27:59] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:27:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/D:/Curse/Minecraft/Instances/Dungeons,%20Dragons%20and%20Space%20Shuttles/mods/malisiscore-1.12.2-6.4.0.jar Service=LaunchWrapper Env=CLIENT
[21:27:59] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:59] [main/WARN]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[21:27:59] [main/INFO]: Compatibility level set to JAVA_8
[21:27:59] [main/INFO]: Initializing VanillaFix
[21:28:00] [main/INFO]: Initializing StacktraceDeobfuscator
[21:28:00] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[21:28:00] [main/INFO]: Done initializing StacktraceDeobfuscator
[21:28:00] [main/INFO]: Initializing Bug Fix Mixins
[21:28:00] [main/INFO]: Initializing Crash Fix Mixins
[21:28:00] [main/INFO]: Initializing Profiler Improvement Mixins
[21:28:00] [main/INFO]: Initializing Texture Fix Mixins
[21:28:00] [main/INFO]: Initializing Mod Support Mixins
[21:28:00] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[21:28:00] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:28:00] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:28:00] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:28:00] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:28:00] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:28:00] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:28:00] [main/INFO]: Calling tweak class io.github.lxgaming.sledgehammer.launch.SledgehammerTweaker
[21:28:00] [main/WARN]: Mixin config mixins.sledgehammer.preinit.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied.
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.sledgehammer.preinit.json requires mixin subsystem version 0.7.10
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.sledgehammer.launch.SledgehammerLaunch.configureEnvironment(SledgehammerLaunch.java:66)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.sledgehammer.launch.SledgehammerTweaker.injectIntoClassLoader(SledgehammerTweaker.java:61)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:28:00] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Freebi85** [comment]
This is more a twitch launcher issue. Try to reinstall the pack to a new profile. This solves the problem iirc. If not join our helpdesk channel in our discord server so we can help you there :)
