### ISSUE TITLE
Issue running the startserver.bat

### ISSUE THREAD

**Issue by haddad5** [Freebi85/Dungeons-Dragons-Space-Shuttles#526]
Just got this computer, and I wanted to make a server so my friends and I could start playing.  I downloaded the server from:

https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles/files/2831468

and after downloading it I unzipped it into a folder on my desktop.  I double clicked the startserver.bat and realized that I hadn't installed java yet after receiving the error "java is not a recognized internal or external command".  Fixed that after installing java and updating the JAVA_HOME and path variables, I ran the startserver.bat again.  First error is gone, but as in programming, another one appeared.  Here is the log after double clicking serverstart.bat:

C:\Users\bvhad\OneDrive\Desktop\Server>java -Xms1024M -Xmx6048M -jar forge-1.12.2-14.23.5.2847-universal.jar nogui
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

C:\Users\bvhad\OneDrive\Desktop\Server>pause
Press any key to continue . . .

Any help would be appreciated.

**Comment by Freebi85** [comment]
Hey =)
Pls join our tech support channel in my Discord for server-side problems or general help with server setups.  As the template already mentions, no server issues are discussed or resolved here.
