### ISSUE TITLE
Kicks other players from the server after death or when logging in after change online-mode to false

### ISSUE THREAD

**Issue by Retried** [Freebi85/Dungeons-Dragons-Space-Shuttles#534]
[14:04:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@6d20cf2d:
java.lang.NullPointerException: Igorasek_PL is not online!
        at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getPlayer(ForgePlayer.java:265) ~[ForgePlayer.class:?]
        at com.feed_the_beast.ftbutilities.data.FTBUtilitiesPlayerData.clearCache(FTBUtilitiesPlayerData.java:316) ~[FTBUtilitiesPlayerData.class:?]
        at com.feed_the_beast.ftblib.lib.data.NBTDataStorage.clearCache(NBTDataStorage.java:123) ~[NBTDataStorage.class:?]
        at com.feed_the_beast.ftblib.lib.data.ForgePlayer.clearCache(ForgePlayer.java:105) ~[ForgePlayer.class:?]
        at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_232]
        at com.feed_the_beast.ftblib.lib.data.Universe.clearCache(Universe.java:842) ~[Universe.class:?]
        at com.feed_the_beast.ftblib.FTBLibEventHandler.onPlayerTick(FTBLibEventHandler.java:27) ~[FTBLibEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_398_FTBLibEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Retried** [comment]
New world
