### ISSUE TITLE
Error Netty Server Io 

### ISSUE THREAD

**Issue by Sadlyxo** [Freebi85/Dungeons-Dragons-Space-Shuttles#946]
Hi I run a sever for the mod Dungeons Dragons and Space Shuttles. I play with a few friends but one of them has issues with his whole Minecraft client crashing when playing this mod. He had already ran the mod fine for a whole day but today he was met with crashes and errors. He runs the mod through twitch client but he has tried multimc client and the regular Minecraft launcher and manually puts all the mods in the mod folder and still gets the same errors. Down below will be some system specs and the Error code I receive on the sever before he disconnect, freezes and crashes. Any help will be appreciated

### System Specs
Cpu: AMD FX(TM)-6100 4c/4t 
Ram: 24gb of ddr3
Gpu: Quadro 5000
Storage:(SSD with sufficient space)
Disclaimer: he ran the mod for a whole day but now its crashing

### Error Code
[Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_271]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_271]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_271]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_271]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_271]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by Freebi85** [comment]
Moved to Discord.
